# Generated by Django 2.0.6 on 2018-06-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('previous_position', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('pot', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
                ('pot', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('previous_position', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sweepstake.Team'),
        ),
        migrations.AddField(
            model_name='participant',
            name='assist_king',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_king', to='Sweepstake.Player'),
        ),
        migrations.AddField(
            model_name='participant',
            name='teams',
            field=models.ManyToManyField(to='Sweepstake.Team'),
        ),
        migrations.AddField(
            model_name='participant',
            name='topscorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topscorer', to='Sweepstake.Player'),
        ),
    ]
