# Generated by Django 2.0.6 on 2018-06-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweepstake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='previous_position',
            field=models.IntegerField(default=0),
        ),
    ]
