# Generated by Django 2.0.6 on 2018-06-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweepstake', '0003_fixture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-points']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-points']},
        ),
        migrations.AddField(
            model_name='fixture',
            name='matchday',
            field=models.IntegerField(default=0),
        ),
    ]
