# Generated by Django 2.0.6 on 2018-07-05 19:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweepstake', '0004_auto_20180628_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='score_status',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='previous_position',
        ),
        migrations.RemoveField(
            model_name='team',
            name='previous_position',
        ),
        migrations.AddField(
            model_name='fixture',
            name='counted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='penalties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='penalty_away_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='penalty_home_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='points_loser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='points_winner',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='participant',
            name='previous_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0}),
        ),
        migrations.AddField(
            model_name='team',
            name='previous_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
