# Generated by Django 2.0.6 on 2018-07-08 20:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweepstake', '0005_auto_20180705_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='goals_away_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='goals_home_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='penalties',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='penalty_away_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='penalty_home_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='points_loser',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='points_winner',
        ),
        migrations.AddField(
            model_name='fixture',
            name='fd_id',
            field=models.IntegerField(default=0, verbose_name='Football-data id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixture',
            name='points',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'loser': 0, 'winner': 2}),
        ),
        migrations.AddField(
            model_name='fixture',
            name='score',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='fixture',
            name='stage',
            field=models.CharField(default='Group', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixture',
            name='matchday',
            field=models.IntegerField(blank=True),
        ),
    ]
