# Generated by Django 2.0.6 on 2018-07-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweepstake', '0006_auto_20180708_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='matchday',
            field=models.IntegerField(null=True),
        ),
    ]
