# Generated by Django 2.0.6 on 2018-09-20 12:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweepstake', '0007_auto_20180708_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='fd_id',
            field=models.IntegerField(unique=True, verbose_name='Football-data id'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='previous_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='team',
            name='pot',
            field=models.IntegerField(default=0),
        ),
    ]
